# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

eval_ <- function(strings, quiet) {
    .Call(`_fasteval_eval_`, strings, quiet)
}

eval_vars_ <- function(strings, list_of_values, quiet) {
    .Call(`_fasteval_eval_vars_`, strings, list_of_values, quiet)
}

